# =============================================================

# 영화 데이터 전처리 ver.1

### Categorical value => dummy variable

# =============================================================

In [1]:
import pandas as pd

df = pd.read_excel('movie_data.xlsx',sheetname = 1)
df.head()

,Name,Code,Genre,Level,RunningTime,Country,Released,Published,Win,WholeAud,SeoulAud,PoSA,NoScreen,NoShow,BoxOffice,TV,Score,Rescreen
0,바람피기 좋은 날,20060421,drama,adult,103,korea,2007-02-08,2007,0,1708979,551815,32.3,1016,39823,1,0,5.77,0
1,운명의 산 낭가 파르밧,20134142,drama,all,104,germany,2013-12-12,2010,0,805,530,65.8,13,64,0,0,7.61,1
2,"색, 계",20070582,drama,adult,157,usa,2007-11-08,2007,0,1924678,735351,38.2,1335,40654,1,0,8.51,1
3,철콘 근크리트,20070394,ani,over15,110,japan,2007-08-02,2006,0,280,280,100.0,4,24,0,0,8.24,1
4,데스노트 : 라스트 네임,20060405,crime,over12,139,japan,2007-01-10,2006,0,563056,147103,26.1,560,14439,0,0,8.27,0

In [4]:
# 모델링에 방해되는 일부 columns 삭제
df1 = df.drop(['Name','Code','Released','SeoulAud','NoScreen'], axis = 1)
df1.head()

,Genre,Level,RunningTime,Country,Published,Win,WholeAud,PoSA,NoShow,BoxOffice,TV,Score,Rescreen
0,drama,adult,103,korea,2007,0,1708979,32.3,39823,1,0,5.77,0
1,drama,all,104,germany,2010,0,805,65.8,64,0,0,7.61,1
2,drama,adult,157,usa,2007,0,1924678,38.2,40654,1,0,8.51,1
3,ani,over15,110,japan,2006,0,280,100.0,24,0,0,8.24,1
4,crime,over12,139,japan,2006,0,563056,26.1,14439,0,0,8.27,0

In [5]:
# 더미변수로 바꿔야하는 columns
df2 = pd.concat([df1.ix[:,0:2],df1.ix[:,3]],axis = 1) 
df2.head()

   Genre   Level  Country
0  drama   adult    korea
1  drama     all  germany
2  drama   adult      usa
3    ani  over15    japan
4  crime  over12    japan

In [6]:
# 더미변수로 변환
Genre_d = pd.get_dummies(df2['Genre'])
Level_d = pd.get_dummies(df2['Level'])
Country_d = pd.get_dummies(df2['Country'])
print Genre_d.shape
print Level_d.shape
print Country_d.shape

# 더미변수로 바꾸면 변수가 3개에서 80개로 바뀐다.

(2000, 20)
(2000, 4)
(2000, 56)

In [7]:
# 더미변수끼리 모으기
dummies0 = Genre_d.ix[:,:'war'].join(Level_d.ix[:,'all':])
dummies = dummies0.join(Country_d.ix[:,:'usa'])
dummies.head()

,SF,action,adventure,ani,comedy,crime,documentary,drama,erotic,family,...,singapore,southafranceica,spain,sweden,swiss,tai,tailand,taiwan,uruguay,usa
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# 원래 데이터프레임에서 카테고리값을 가진 변수를 삭제하고 더미변수 이어붙이기
df3 = df1.drop(['Genre','Level','Country'],axis =1)
df3 = df3.join(dummies)
df3

,RunningTime,Published,Win,WholeAud,PoSA,NoShow,BoxOffice,TV,Score,Rescreen,...,singapore,southafranceica,spain,sweden,swiss,tai,tailand,taiwan,uruguay,usa
0,103,2007,0,1708979,32.3,39823,1,0,5.77,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,104,2010,0,805,65.8,64,0,0,7.61,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,157,2007,0,1924678,38.2,40654,1,0,8.51,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,110,2006,0,280,100.0,24,0,0,8.24,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,139,2006,0,563056,26.1,14439,0,0,8.27,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,126,2010,0,77539,44.3,5410,0,0,8.85,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,120,2006,0,59648,63.4,2106,0,0,7.50,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,68,2012,0,9,100.0,4,0,0,3.94,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,89,2013,0,599,33.4,30,0,0,8.37,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,77,2013,0,656,30.6,22,0,0,5.32,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,83,2013,0,528,100.0,2,0,0,8.01,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,118,2006,0,32156,41.8,2538,0,0,8.98,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,95,2010,0,79884,24.0,3062,0,0,8.60,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,121,2013,0,3117859,20.5,55047,1,1,7.10,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,98,2011,1,504,85.1,56,0,0,6.98,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,124,2009,0,1670652,28.4,57064,1,0,6.94,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,131,2011,0,4421210,31.0,70562,1,0,9.31,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,146,2010,0,2853500,30.6,52466,1,0,8.20,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,112,2013,0,1048280,21.5,36401,0,0,7.32,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,91,2008,0,107929,25.2,9748,0,0,7.99,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20,94,2011,0,373996,63.2,10520,0,0,8.54,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,156,2010,1,2260512,31.6,41947,0,0,7.76,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,139,2008,0,6686054,30.1,93328,1,1,7.73,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,112,2008,1,4039891,29.0,90526,1,1,8.28,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,63,2008,0,307,100.0,64,0,0,6.03,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,95,2009,0,10783,61.6,1456,0,0,7.75,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,116,2011,0,62825,47.3,3327,0,0,7.98,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,64,2011,0,256,100.0,77,0,0,6.40,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,116,2011,0,73981,81.7,2402,0,0,8.23,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,101,2007,0,50289,66.7,839,0,0,7.70,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,103,2006,0,915370,27.9,24234,1,0,5.83,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1971,116,2006,0,42924,78.8,878,0,0,7.53,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1972,86,2006,0,299171,28.5,8619,0,0,7.41,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1973,112,2006,0,160315,27.3,8751,0,0,6.08,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1974,106,2003,0,730,89.2,30,0,0,7.72,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1975,107,2005,0,136,100.0,24,0,0,6.43,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1976,121,2006,0,35536,65.8,1417,0,0,8.96,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1977,108,2006,0,51,70.6,29,0,0,6.97,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1978,116,2005,0,6076,60.6,440,0,0,7.63,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1979,112,2006,0,29880,26.2,1498,0,0,8.15,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1980,107,2006,0,950,84.0,154,0,0,6.22,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1981,118,2006,0,50745,40.7,3118,0,0,8.26,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1982,89,2006,0,1575,92.2,139,0,0,7.59,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1983,112,2006,0,642,93.6,128,0,0,7.53,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,97,2006,0,22,50.0,10,0,0,3.75,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1985,96,2006,0,5285,100.0,239,0,0,6.58,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1986,100,2005,0,44,100.0,12,0,0,6.91,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1987,131,2005,0,2,100.0,1,0,0,7.23,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1988,101,2006,0,1141,35.8,255,0,0,6.51,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1989,113,2003,0,161,100.0,18,0,0,9.00,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1990,117,2006,0,126,50.8,13,0,0,7.50,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1991,93,2006,0,372,100.0,52,0,0,8.14,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1992,93,2010,0,170,76.5,46,0,0,6.90,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1993,105,2011,0,156744,35.6,10501,0,0,6.41,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1994,103,2011,0,228899,42.6,12963,0,0,6.77,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1995,116,2011,0,165123,35.2,10850,0,0,7.24,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1996,84,2011,0,191783,17.5,5316,0,0,7.11,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1997,92,2011,0,257193,34.0,9248,0,0,6.54,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1998,60,2011,0,2119,87.7,72,0,0,7.70,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1999,128,2009,0,10,100.0,1,0,0,4.44,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df3.describe(include='all')

,RunningTime,Published,Win,WholeAud,PoSA,NoShow,BoxOffice,TV,Score,Rescreen,...,singapore,southafranceica,spain,sweden,swiss,tai,tailand,taiwan,uruguay,usa
count,2000.000000,2000.000000,2000.000000,2.000000e+03,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,103.646500,2009.123500,0.071500,4.015309e+05,59.339650,9475.978500,0.095500,0.052500,7.209955,0.168500,...,0.001000,0.001000,0.02100,0.007000,0.001000,0.005000,0.003000,0.00250,0.001000,0.273500
std,19.859878,4.206911,0.257723,1.237832e+06,29.329086,21709.066305,0.293978,0.223089,1.524196,0.374403,...,0.031615,0.031615,0.14342,0.083394,0.031615,0.070551,0.054704,0.04995,0.031615,0.445867
min,40.000000,1957.000000,0.000000,0.000000e+00,1.800000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,91.000000,2007.000000,0.000000,9.250000e+02,31.200000,56.750000,0.000000,0.000000,6.510000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,101.500000,2010.000000,0.000000,6.663000e+03,57.250000,473.000000,0.000000,0.000000,7.525000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
75%,114.000000,2012.000000,0.000000,1.377700e+05,87.725000,7191.000000,0.000000,0.000000,8.302500,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000
max,310.000000,2013.000000,1.000000,1.330264e+07,100.000000,203443.000000,1.000000,1.000000,10.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [10]:
df3.to_excel("preprocess0.xlsx")